pur_beurre/main_site/urls.py
from django.urls import path

from . import views

app_name = 'main_site'
urlpatterns = [
    path('', views.home, name='home'),
    path('aliment/<product_id>/', views.product_description, name='product'),
    path('notice/', views.legal_notice, name='notice'),
    path('research/', views.product_research, name='research'),
    path('research_category/', views.category_research, name='research_category'),
    path('category_products/<category_id>/', views.products_of_category, name='category_products'),
    path('account/', views.account_detail, name='account'),
    path('favorites/', views.favorites, name='favorites'),
    path('add-favorite/', views.add_favorite, name='add-favorite')
]

pur_beurre/pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('', include('main_site.urls')),
]

pur_beurre/user_management/urls.py
from django.urls import path, include

from . import views

app_name = 'user_management'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

pur_beurre/main_site/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    url = models.CharField(max_length=200, unique=True)
    nutriscore = models.CharField(max_length=1)
    users = models.ManyToManyField(User, blank=True, null=True)
    img_url = models.CharField(max_length=200, unique=True)
    kcal = models.IntegerField()
    fat = models.IntegerField()
    protein = models.IntegerField()
    sugar = models.IntegerField()
    
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    products = models.ManyToManyField(Product)

    def __str__(self):
        return self.name

pur_beurre/user_management/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from main_site.models import Product

class UserExtension(AbstractUser):
    email = models.EmailField(unique=True)

    REQUIRED_FIELDS = ['username']
    USERNAME_FIELD = 'email'

pur_beurre/user_management/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Nom d\'utilisateur')

pur_beurre/main_site/views.py
import string
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from main_site.models import Product, Category
from django.contrib.postgres.search import TrigramWordSimilarity
from django.urls import reverse

# Create your views here.

def home(request):

    return render(request, 'main_site/welcome_page.html')

def account_detail(request):

    # Checking if user is authentificated
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user_management:signup'))

    context  = {
        "username" : request.user.username,
        "email" : request.user.email
    }

    return render(request, 'main_site/account_detail.html', context)

def legal_notice(request):

    return render(request, 'main_site/legal_notice.html')
  
def product_description(request, product_id):
    favorite_products = []
    substitute_products = []
    best_subsitute_products = []
    nutriscore_count = 0
    product = Product.objects.get(id=product_id)

    # Checking if user is authentificated
    if request.user.is_authenticated:
        favorite_products = request.user.product_set.all()

    # Creating the list of products with better nutriscore than the main one
    for categories in product.category_set.all():
        for linked_product in categories.products.all():
            if string.ascii_uppercase.index(linked_product.nutriscore) <= string.ascii_uppercase.index(product.nutriscore) and linked_product not in substitute_products and linked_product != product:
                substitute_products.append(linked_product)

    # Creating the list with the bests nutriscore from the first list
    while nutriscore_count < 4:
        for best_product in substitute_products:
            if len(best_subsitute_products) >= 6:
                break
            if string.ascii_uppercase.index(best_product.nutriscore) == nutriscore_count:
                best_subsitute_products.append(best_product)
        nutriscore_count += 1

    context = {
        "focused_product" : product,
        "substitute_products" : best_subsitute_products,
        "favorite_products" : favorite_products,
    }

    return render(request, 'main_site/product_description_page.html', context)

def product_research(request):

    # Executing the trigram research
    research_result = Product.objects.annotate(
        similarity=TrigramWordSimilarity(f'{request.GET.get("product_searched")}', "name")
    ).filter(similarity__gte=0.5).order_by('-similarity')


    context = {
        "results": research_result,
    }

    return render(request, 'main_site/product_research.html', context)

def category_research(request):

    # Executing the trigram research
    research_result = Category.objects.annotate(
        similarity=TrigramWordSimilarity(f'{request.GET.get("category_searched")}', "name")
    ).filter(similarity__gte=0.5).order_by('-similarity')


    context = {
        "results": research_result,
    }

    return render(request, 'main_site/category_research.html', context)

def products_of_category(request, category_id):

    category_products = []

    category = Category.objects.get(id=category_id)

    for products in category.products.all():
        category_products.append(products)
    
    context = {
        "results": category_products,
    }

    return render(request, 'main_site/product_research.html', context)        

def favorites(request):
    favorite_message = "Produits favoris"

    # Checking if user is authentificated
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user_management:login'))

    favorite_products = request.user.product_set.all()

    if list(favorite_products) == []:
        favorite_message = "Vous n'avez aucun produit favori"

    context  = {
        "favorite_message" : favorite_message,
        "favorite_products" : favorite_products,
    }

    return render(request, 'main_site/favorite_page.html', context)

def add_favorite(request):
    
    # Checking if user is authenticated
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user_management:signup'))

    product_id = request.POST.get("product_id")
    product = Product.objects.get(id=product_id)
    user_connected = request.user
    favorite_products = user_connected.product_set.all()

    if product not in favorite_products:
        product.users.add(user_connected)
    else:
        product.users.remove(user_connected)

    return HttpResponseRedirect(f'/aliment/{product_id}/')

pur_beurre/user_management/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, get_user_model, views

from .forms import SignUpForm, LoginForm


User = get_user_model()

class LoginView(views.LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('main_site:home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

pur_beurre/main_site/templates/main_site/account_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Compte{% endblock title %}

{% block content %}
<div class="row bg-image bg-img-user">
    <h1 class="row justify-content-center my-3">Bonjour {{ username }} !</h1>
    <p class="row justify-content-center fs-4 my-4">Email : {{ email }}</p>
    <h2 class="row justify-content-center my-5">{{ favorite_message }}</h2>
</div>
{% endblock content %}

pur_beurre/main_site/templates/main_site/category_research.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Recherche{% endblock title %}

{% block content %}
<form class = "row justify-content-center my-5" action = "/research_category/" method = "get">
    {% csrf_token %}
    <div class="col-1"></div>
    <input class="col-6 col-sm-5 col-md-4 col-lg-3" id="category_searched" type="text" name="category_searched" placeholder="Recherche par catégorie">
    <div class="col-1">
        <input class="btn btn-primary" type="submit" value="Rechercher">
    </div>
</form>
<div class="row">
    {% for category in results %}
        <div class="col-12 col-sm-6 col-lg-4">
            <a href="{% url 'main_site:category_products' category.id %}">
                <div>
                    <h2 class="col text-center my-4">{{ category.name }}</h2>
                </div>
                <div class="row h4 mt-3 mb-5">
                    <div class="col text-center">
                        <span class="badge rounded-pill mussels-bg">{{ category.nutriscore }}</span>
                    </div>
                </div>
                <div class="row justify-content-center mb-5">
                    <a class="col category-presentation text-center"></a>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock content %}

pur_beurre/main_site/templates/main_site/favorite_page.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Favoris{% endblock title %}

{% block content %}
<h2 class="row justify-content-center my-5">{{ favorite_message }}</h2>
<div class="row">
    {% for product in favorite_products %}
        <div class="col-4">
            <div>
                <h2 class="col text-center my-4">{{ product.name }}</h2>
            </div>
            <div class="row h4 mt-3 mb-5">
                <div class="col text-center">
                    <span class="badge rounded-pill mussels-bg">{{ product.nutriscore }}</span>
                </div>
            </div>
            <div class="row justify-content-center mb-5">
                <a class="col product-presentation text-center" href="{% url 'main_site:product' product.id %}">
                    <img class="substitution-product-img" src="{{ product.img_url }}">
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

pur_beurre/main_site/templates/main_site/legal_notice.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Mentions légales{% endblock title %}
{% block content %}
<h1 class="row justify-content-center">Mentions légales</h1>
<ul class="row justify-content-center">
    <li class="row justify-content-center">Image de fond : Kawin Harasai</li>
    <li class="row justify-content-center">Logo d'utilisateur : WMF User Experience Design group</li>
    <li class="row justify-content-center">Logo de carotte : Fabien Jouin</li>
    <li class="row justify-content-center">Logo de déconnexion : Dave Gandy</li>
    <li class="row justify-content-center">Logo de téléphone : yupiramos</li>
    <li class="row justify-content-center">Logo de mail : panom73</li>
    <li class="row justify-content-center">Image de fond utilisateur : Olenka Kotyk</li>
</ul>
{% endblock content %}

pur_beurre/main_site/templates/main_site/product_description_page.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Aliment{% endblock title %}

{% block content %}
<div class="row">
    <h2 class="col-12 col-lg-11 col-xl-10 text-center my-4">{{ focused_product.name }}</h2>
</div>
<div class="row h4 mt-3 mb-5">
    <div class="col-12 col-lg-11 col-xl-10 text-center">
        <span class="badge rounded-pill mussels-bg">{{ focused_product.nutriscore }}</span>
    </div>
</div>
<div class="row justify-content-center">
    <a class="col-12 col-lg-9 col-xl-8 product-presentation text-center mb-5" href="{{ focused_product.url }}">
        <img class="focused-product-img" src="{{ focused_product.img_url }}">
    </a>
    <div class="col-6 col-md-5 col-lg-2 mt-2">
        <h3 class="text-center">Valeur nutritive</h3>
        <table class="table bg-light rounded">
            <tbody>
                <tr>
                    <th scope="row">Kcal/100g</th>
                    <td>{{ focused_product.kcal }}</td>
                </tr>
                <tr>
                    <th scope="row">Lipides/100g</th>
                    <td>{{ focused_product.fat }}</td>
                </tr>
                <tr>
                    <th scope="row">Protéines/100g</th>
                    <td>{{ focused_product.protein }}</td>
                </tr>
                <tr>
                    <th scope="row">Glucides/100g</th>
                    <td>{{ focused_product.sugar }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<form class="row justify-content-center mt-5" method="post" action="{% url 'main_site:add-favorite' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ focused_product.id }}"></input>
    <button type="submit" class="fs-1 disk-button" style="{% if focused_product not in favorite_products %} color:rgba(0, 0, 0, 0.5){% endif %}">💾</button>
</form>
<hr class="my-5">
<h2 class="row justify-content-center">Produits de substitution</h2>
<div class="row">
    {% for product in substitute_products %}
        <div class="col-12 col-sm-6 col-lg-4">
            <div>
                <h2 class="col text-center my-4">{{ product.name }}</h2>
            </div>
            <div class="row h4 mt-3 mb-5">
                <div class="col text-center">
                    <span class="badge rounded-pill mussels-bg">{{ product.nutriscore }}</span>
                </div>
            </div>
            <div class="row justify-content-center mb-5">
                <a class="col product-presentation text-center" href="{% url 'main_site:product' product.id %}">
                    <img class="substitution-product-img" src="{{ product.img_url }}">
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

pur_beurre/main_site/templates/main_site/product_research.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Recherche{% endblock title %}

{% block content %}
<form class = "row justify-content-center mt-5" action = "/research/" method = "get">
    <div class="col-1"></div>
    <input class="col-6 col-sm-5 col-md-4 col-lg-3" id="product_searched" type="text" name="product_searched" placeholder="Recherche de produit">
    <div class="col-1">
        <input class="btn btn-primary" type="submit" value="Rechercher">
    </div>
</form>
<div class="row">
    {% for product in results %}
        <div class="col-12 col-sm-6 col-lg-4">
            <div>
                <h2 class="col text-center my-4">{{ product.name }}</h2>
            </div>
            <div class="row h4 mt-3 mb-5">
                <div class="col text-center">
                    <span class="badge rounded-pill mussels-bg">{{ product.nutriscore }}</span>
                </div>
            </div>
            <div class="row justify-content-center mb-5">
                <a class="col product-presentation text-center" href="{% url 'main_site:product' product.id %}">
                    <img class="substitution-product-img" src="{{ product.img_url }}">
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

pur_beurre/main_site/templates/main_site/welcome_page.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Accueil{% endblock title %}

{% block content %}
<div>
    <h1 class="row justify-content-center mt-5">Du gras, oui, mais de qualité !</h1>
    <h2 class="row justify-content-center mt-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
        <form class = "row justify-content-center mt-5" action = "/research/" method = "get">
            {% csrf_token %}
            <div class="col-1"></div>
            <input class="col-6 col-sm-5 col-md-4 col-lg-3" id="product_searched" type="text" name="product_searched" placeholder="Recherche de produit">
            <div class="col-1">
                <input class="btn btn-primary" type="submit" value="Rechercher">
            </div>
        </form>
        <form class = "row justify-content-center mt-5" action = "/research_category/" method = "get">
            {% csrf_token %}
            <div class="col-1"></div>
            <input class="col-6 col-sm-5 col-md-4 col-lg-3" id="category_searched" type="text" name="category_searched" placeholder="Recherche par catégorie">
            <div class="col-1">
                <input class="btn btn-primary" type="submit" value="Rechercher">
            </div>
        </form>
</div>
<hr class="my-5">
<h2 class="row justify-content-center">Colette et Remy</h2>
<figcaption class="row justify-content-center blockquote-footer"></figcaption>
<h3 class="h4">De la ratatouille aux croissants</h3>
<p class="mb-5">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
<div class="row justify-content-center mt-5">
    <p class="col-5 col-sm-4 col-md-3 col-lg-2 col-xl-1 fs-3 text-center">Colette</p>
    <div class="col-1"></div>
    <p class="col-5 col-sm-3 col-md-1 fs-3 text-center">Remy</p>
</div>
<div class="row justify-content-center">
    <img class="col-4 img-fluid" style="height: 499px; width: 230px" src="{% static 'main_site/img/colette-tatou-portrait.png' %}">
    <img class="col-4 img-fluid mt-5" style="height: 499px; width: 230px" src="{% static 'main_site/img/remy-portrait.png' %}">
</div>
<div class="row">
    <p class="col-6">
        <strong>Colette Tatou :</strong> "Nous aimons tous manger, surtout en France !
        Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement.
        Comme tout le monde, je fais mes courses au supermarché.
        Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant,
        que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"
    </p>
    <p class="col-6">
        <strong>Remy :</strong> "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines.
        Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus.
        Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver.
        L'idée de Pur Beurre était née !"
    </p>
</div>
<hr class="yt-5">
<h2 class="row justify-content-center">Contactez-nous !</h2>
<div class="row justify-content-center">
    <div class="col col-md-3" align="center">
        <img class="col-sm-1 img-fluid" style="height: 130px; width: 90px" src="{% static 'main_site/img/phone-logo.png' %}">
    </div>
    <div class="col col-md-3" align="center">
        <img class="col-sm-1 img-fluid mt-4" style="height: 100px; width: 150px" src="{% static 'main_site/img/mail-logo.png' %}">
    </div>
</div>
<div class="row justify-content-center">
    <p class="col col-md-3 fs-3 text-center">00 00 00 00 00</p>
    <p class="col col-md-3 fs-3 text-center">mail@mail.com</p>
</div>
{% endblock content %}

pur_beurre/templates/base/base.html
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Page title{% endblock title %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'main_site/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'main_site/css/style.css' %}">
  <script src="{% static 'js/script.js' %} "></script>
</head>
<body class="container-fluid bg-image bg-img">
    <header class="row align-items-center justify-content-center">
      <a class="col-4 col-xs-3 col-sm-2 col-md-1" href="{% url 'main_site:home' %}"><img class="img-fluid header-logo" src="{% static 'main_site/img/pur_beurre_logo.png' %}"></a>
      <h1 class="col-6 col-sm-4">Pur beurre</h1>
      <form class="col-12 col-xs-10 col-sm-6 col-md-4 col-lg-3" action = "/research/" method = "get">
        <input class="col-9" id="product_searched" type="text" name="product_searched" placeholder="Recherche de produit">
        <input class="btn btn-secondary col-2"  type="submit" value="OK">
      </form>
      <a class="col-4 col-md-1 text-center" href="{% url 'main_site:account' %}"><img class="img-fluid header-logo" src="{% static 'main_site/img/user-logo.png' %}"></a>
      <a class="col-4 col-md-1 text-center" href="{% url 'main_site:favorites' %}"><img class="img-fluid header-logo" src="{% static 'main_site/img/carrot-logo.png' %}"></a>
      {% comment %} Contribution de Jeremy, le roi de Symfony. {% endcomment %}
      {% if user.is_authenticated %}
      <a class="col-4 col-md-1 text-center" href="{% url 'user_management:logout' %}"><img class="img-fluid header-logo" src="{% static 'main_site/img/deconection-logo.png' %}"></a>
      {% endif %}
    </header>
    <section>
        {% block content %}Page contents{% endblock content %}
    </section>
    <div>ㅤ</div>
    <footer class="row justify-content-center fixed-bottom">
      <hr>
      <a class="col-6 text-center text-decoration-none text-dark" href="{% url 'main_site:notice' %}"><strong>Mentions légales</strong></a>
      <a class="col-6 text-center text-decoration-none text-dark" href="mailto:mail@mail.com"><strong>Contact</strong></a>
    </footer>
</body>
</html>